import {fontSize, gutter, radius, spacing, typographyPresets} from '../tokens';
import type {AppTheme} from '../types';

export const darkTheme: AppTheme = {
  id: 'dark',
  name: 'Tối',
  colors: {
    background: '#0b1120',
    surface: '#1e293b',
    surfaceMuted: '#0f172a',
    surfaceLow: '#0f172a',
    surfaceContainer: '#1e293b',
    surfaceHigh: '#334155',
    border: '#334155',
    outline: '#475569',
    outlineVariant: '#334155',
    primary: '#3b82f6',
    primaryPressed: '#2563eb',
    primaryContainer: '#1d4ed8',
    onPrimaryContainer: '#dbeafe',
    secondary: '#94a3b8',
    secondaryContainer: '#7f1d1d',
    secondarySoft: 'rgba(248,113,113,0.18)',
    onSecondaryContainer: '#fecaca',
    tertiary: '#fcd34d',
    tertiaryContainer: '#a16207',
    tertiaryFixed: '#fde68a',
    tertiarySoft: 'rgba(252,211,77,0.18)',
    onTertiaryContainer: '#fef9c3',
    accent: '#22d3ee',
    accentInk: '#083344',
    accentSoft: 'rgba(34,211,238,0.16)',
    danger: '#f87171',
    text: {
      primary: '#f8fafc',
      secondary: '#cbd5e1',
      inverse: '#0b1120',
      muted: '#94a3b8',
    },
  },
  states: {disabledOpacity: 0.5, pressedOpacity: 0.8},
  typography: {
    fontFamily: {},
    size: {...fontSize},
    weight: {regular: '400', medium: '600', bold: '800'},
    presets: {...typographyPresets},
  },
  gutter,
  spacing: {...spacing},
  radius: {...radius},
  shadow: {
    soft: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 1,
    },
    medium: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.4,
      shadowRadius: 6,
      elevation: 3,
    },
    strong: {
      shadowColor: '#000000',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.5,
      shadowRadius: 12,
      elevation: 6,
    },
  },
  components: {
    button: {
      primary: {background: '#3b82f6', text: '#0b1120', height: 48, radius: 8},
      secondary: {
        background: 'transparent',
        text: '#f8fafc',
        border: '#334155',
        height: 44,
        radius: 8,
      },
    },
    card: {background: '#1e293b', radius: 8, padding: 12, shadow: 'medium'},
    input: {
      background: '#1e293b',
      text: '#f8fafc',
      placeholder: '#64748b',
      border: '#334155',
      radius: 8,
    },
  },
};
