import {fontSize, gutter, typographyPresets} from '../tokens';
import type {AppTheme} from '../types';

const handoffSpacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
  xxxl: 48,
};

export const pastelKidsTheme: AppTheme = {
  id: 'pastel-kids',
  name: 'Pastel Kids',
  colors: {
    background: '#fcfae6',
    surface: '#ffffff',
    surfaceMuted: '#f5f2d8',
    surfaceLow: '#f6f4e1',
    surfaceContainer: '#f0efdb',
    surfaceHigh: '#ebe9d5',
    border: '#6a7975',
    outline: '#6b7a76',
    outlineVariant: '#bacac5',
    primary: '#006b5f',
    primaryPressed: '#00574d',
    primaryContainer: '#2dd4bf',
    onPrimaryContainer: '#00574d',
    secondary: '#a93349',
    secondaryContainer: '#fe7488',
    secondarySoft: 'rgba(254,116,136,0.18)',
    onSecondaryContainer: '#730425',
    tertiary: '#6d5e00',
    tertiaryContainer: '#d8bd23',
    tertiaryFixed: '#ffe24c',
    tertiarySoft: 'rgba(255,226,76,0.30)',
    onTertiaryContainer: '#594c00',
    accent: '#2dd4bf',
    accentInk: '#00574d',
    accentSoft: 'rgba(45,212,191,0.16)',
    danger: '#ba1a1a',
    overlayLight: 'rgba(255,255,255,0.34)',
    overlay: 'rgba(0,0,0,0.55)',
    onOverlay: '#ffffff',
    tertiaryBorder: 'rgba(255,226,76,0.45)',
    text: {
      primary: '#1c1c10',
      secondary: '#3c4a46',
      inverse: '#ffffff',
      muted: '#5f6e6a',
    },
  },
  states: {disabledOpacity: 0.38, pressedOpacity: 0.85},
  typography: {
    fontFamily: {display: 'Lexend', primary: 'Quicksand'},
    size: {...fontSize},
    weight: {regular: '400', medium: '600', bold: '700'},
    presets: {...typographyPresets},
  },
  gutter,
  spacing: {...handoffSpacing},
  radius: {sm: 8, md: 18, lg: 24, xl: 32, pill: 999},
  shadow: {
    soft: {
      shadowColor: '#006b5f',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 2,
    },
    card: {
      shadowColor: '#006b5f',
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.07,
      shadowRadius: 30,
      elevation: 8,
    },
    medium: {
      shadowColor: '#2dd4bf',
      shadowOffset: {width: 0, height: 3},
      shadowOpacity: 0.18,
      shadowRadius: 10,
      elevation: 4,
    },
    strong: {
      shadowColor: '#fe7488',
      shadowOffset: {width: 0, height: 5},
      shadowOpacity: 0.22,
      shadowRadius: 14,
      elevation: 6,
    },
    buttonPrimary: {
      shadowColor: '#2dd4bf',
      shadowOffset: {width: 0, height: 10},
      shadowOpacity: 0.40,
      shadowRadius: 22,
      elevation: 8,
    },
    buttonSecondary: {
      shadowColor: '#fe7488',
      shadowOffset: {width: 0, height: 10},
      shadowOpacity: 0.34,
      shadowRadius: 22,
      elevation: 8,
    },
    buttonDeep: {
      shadowColor: '#006b5f',
      shadowOffset: {width: 0, height: 10},
      shadowOpacity: 0.30,
      shadowRadius: 22,
      elevation: 8,
    },
  },
  components: {
    button: {
      'primary-accent': {
        background: '#2dd4bf',
        text: '#00574d',
        height: 52,
        radius: 999,
        shadow: 'buttonPrimary',
      },
      'secondary-coral': {
        background: '#fe7488',
        text: '#ffffff',
        height: 52,
        radius: 999,
        shadow: 'buttonSecondary',
      },
      outline: {
        background: '#ffffff',
        text: '#006b5f',
        border: '#006b5f',
        height: 52,
        radius: 999,
      },
      ghost: {
        background: '#ebe9d5',
        text: '#006b5f',
        height: 52,
        radius: 999,
      },
      deep: {
        background: '#006b5f',
        text: '#ffffff',
        height: 52,
        radius: 999,
        shadow: 'buttonDeep',
      },
    },
    card: {background: '#ffffff', radius: 24, padding: 24, shadow: 'card'},
    input: {
      background: '#ffffff',
      text: '#1c1c10',
      placeholder: '#6b7a76',
      border: '#6b7a76',
      radius: 18,
    },
  },
};
