import {fontSize, gutter, typographyPresets} from '../tokens';
import type {AppTheme} from '../types';

const handoffSpacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  xxl: 32,
  xxxl: 48,
};

export const stickerSoftTheme: AppTheme = {
  id: 'sticker-soft',
  name: 'Sticker',
  colors: {
    background: '#fcfae6',
    surface: '#ffffff',
    surfaceMuted: '#f6f4e1',
    surfaceLow: '#f6f4e1',
    surfaceContainer: '#f0efdb',
    surfaceHigh: '#ebe9d5',
    border: '#566862',
    outline: '#6b7a76',
    outlineVariant: '#bacac5',
    primary: '#006b5f',
    primaryPressed: '#00574d',
    primaryContainer: '#2dd4bf',
    onPrimaryContainer: '#00574d',
    secondary: '#a93349',
    secondaryContainer: '#fe7488',
    secondarySoft: '#ffdfe4',
    onSecondaryContainer: '#5a0017',
    tertiary: '#6d5e00',
    tertiaryContainer: '#d8bd23',
    tertiaryFixed: '#ffe24c',
    tertiarySoft: '#fdeeb8',
    onTertiaryContainer: '#5e4e00',
    accent: '#2dd4bf',
    accentInk: '#00413a',
    accentSoft: '#cdf3ee',
    danger: '#ba1a1a',
    overlayLight: 'rgba(255,255,255,0.34)',
    overlay: 'rgba(0,0,0,0.55)',
    onOverlay: '#ffffff',
    tertiaryBorder: 'rgba(255,226,76,0.45)',
    text: {
      primary: '#1c1c10',
      secondary: '#3c4a46',
      inverse: '#ffffff',
      muted: '#5f6e6a',
    },
  },
  states: {disabledOpacity: 0.38, pressedOpacity: 0.85},
  typography: {
    fontFamily: {display: 'Lexend', primary: 'Quicksand'},
    size: {...fontSize},
    weight: {regular: '400', medium: '600', bold: '800'},
    presets: {
      ...typographyPresets,
      display: {...typographyPresets.display, fontWeight: '800'},
      h1: {...typographyPresets.h1, fontWeight: '800'},
      title: {...typographyPresets.title, fontWeight: '800'},
      h2: {...typographyPresets.h2, fontWeight: '700'},
      h3: {...typographyPresets.h3, fontWeight: '700'},
      label: {...typographyPresets.label, fontWeight: '700'},
      caption: {...typographyPresets.caption, fontWeight: '700'},
    },
  },
  gutter,
  spacing: {...handoffSpacing},
  radius: {sm: 12, md: 18, lg: 22, xl: 28, pill: 999},
  shadow: {
    soft: {},
    medium: {},
    strong: {},
    card: {},
  },
  shelf: {
    surface: {height: 6, color: '#e6e2ca'},
    accent: {height: 6, color: '#17a595'},
    coral: {height: 6, color: '#e05068'},
    primary: {height: 6, color: '#004a41'},
    ghost: {height: 6, color: '#d7d4bf'},
    chipTeal: {height: 5, color: '#a9e2da'},
    chipYellow: {height: 5, color: '#ecd989'},
    chipPink: {height: 5, color: '#f4c1ca'},
    iconButton: {height: 4, color: '#e0dcc4'},
    tabBar: {height: 7, color: '#004a41'},
  },
  components: {
    button: {
      'primary-accent': {
        background: '#2dd4bf',
        text: '#00413a',
        height: 52,
        radius: 999,
      },
      'secondary-coral': {
        background: '#fe7488',
        text: '#5a0017',
        height: 52,
        radius: 999,
      },
      outline: {
        background: '#ffffff',
        text: '#006b5f',
        border: '#006b5f',
        height: 52,
        radius: 999,
      },
      ghost: {
        background: '#ebe9d5',
        text: '#006b5f',
        height: 52,
        radius: 999,
      },
      deep: {
        background: '#006b5f',
        text: '#ffffff',
        height: 52,
        radius: 999,
      },
    },
    card: {background: '#ffffff', radius: 28, padding: 18, shadow: 'card'},
    input: {
      background: '#ffffff',
      text: '#1c1c10',
      placeholder: '#6b7a76',
      border: '#566862',
      radius: 18,
    },
  },
};
