import type {FeatureRegistryEntry} from './types';

export const featureRegistry = [
  {
    key: 'pasteTextInput',
    module: 'src/features/input',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'imageInput',
    module: 'src/features/input',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'ocrScanner',
    module: 'src/features/ocr',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'ocrReviewEdit',
    module: 'src/features/ocr',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'CreateHub -> ImageCapture -> OCRReview',
  },
  {
    key: 'shortPractice',
    module: 'src/features/practice',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'Lesson player -> Practice',
  },
  {
    key: 'pronunciationSupport',
    module: 'src/features/speaking',
    required: false,
    releaseGroup: 'foundation',
    status: 'not_implemented',
    limitations: ['Not implemented yet'],
  },
  {
    key: 'themeSystem',
    module: 'src/ui/theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'themeSwitcher',
    module: 'src/ui/theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'darkTheme',
    module: 'src/ui/theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'pastelKidsTheme',
    module: 'src/ui/theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'coreTheme',
    module: 'src/ui/theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'neoTheme',
    module: 'src/ui/theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'comicTheme',
    module: 'src/ui/theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'cartoonTheme',
    module: 'src/ui/theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'stickerSoftTheme',
    module: 'src/ui/theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'reviewSystem',
    module: 'src/features/review',
    required: false,
    releaseGroup: 'practice',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'miniGame',
    module: 'src/features/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ['Not implemented yet'],
  },
  {
    key: 'wordMatchGame',
    module: 'src/features/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ['Not implemented yet'],
  },
  {
    key: 'fillBlankGame',
    module: 'src/features/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ['Not implemented yet'],
  },
  {
    key: 'tenseQuizGame',
    module: 'src/features/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ['Not implemented yet'],
  },
  {
    key: 'sentenceOrderGame',
    module: 'src/features/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ['Not implemented yet'],
  },
  {
    key: 'flashcardChallenge',
    module: 'src/features/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ['Not implemented yet'],
  },
  {
    key: 'situationLearning',
    module: 'src/features/lesson/player',
    required: false,
    releaseGroup: 'expansion',
    status: 'not_implemented',
    limitations: ['Not implemented yet'],
  },
  {
    key: 'dialogueGenerator',
    module: 'src/features/lesson/player',
    required: false,
    releaseGroup: 'expansion',
    status: 'not_implemented',
    limitations: ['Not implemented yet'],
  },
  {
    key: 'phraseExtractor',
    module: 'src/features/lesson/player',
    required: false,
    releaseGroup: 'expansion',
    status: 'not_implemented',
    limitations: ['Not implemented yet'],
  },
  {
    key: 'situationPractice',
    module: 'src/features/lesson/player',
    required: false,
    releaseGroup: 'expansion',
    status: 'not_implemented',
    limitations: ['Not implemented yet'],
  },
  {
    key: 'youtubeLearning',
    module: 'src/features/lesson/player',
    required: false,
    releaseGroup: 'expansion',
    status: 'beta',
    entryPoint:
      'Home video card -> Lessons/LessonCreation (initialSource youtube) when unified catalog is ready',
  },
] as const satisfies readonly FeatureRegistryEntry[];

export type FeatureKey = (typeof featureRegistry)[number]['key'];

export const featureKeys = featureRegistry.map(entry => entry.key);
