export {
  CURRICULUM_LESSON_FIXTURE_REVISION,
  CURRICULUM_LESSON_SERVER_FIXTURE_SHA,
  CurriculumLessonTextVariantValues,
  CurriculumLessonTextBlockDataSchema,
  CurriculumLessonExampleBlockDataSchema,
  CurriculumLessonVocabularyItemSchema,
  CurriculumLessonMediaAssetSchema,
  CurriculumLessonMultipleChoiceOptionSchema,
  CurriculumLessonMultipleChoiceConfigSchema,
  CurriculumLessonExerciseExplanationSchema,
  CurriculumLessonExerciseSchema,
  CurriculumLessonTextBlockSchema,
  CurriculumLessonExampleBlockSchema,
  CurriculumLessonVocabularyBlockSchema,
  CurriculumLessonMediaBlockSchema,
  CurriculumLessonExerciseBlockSchema,
  CurriculumLessonBlockSchema,
  CurriculumLessonUnsupportedBlockSchema,
  CurriculumLessonAggregateSchema,
  CurriculumLessonAggregateSuccessResponseSchema,
  CurriculumLessonCheckRequestBodySchema,
  CurriculumLessonCheckSuccessResponseSchema,
  CurriculumLessonErrorCodeSchema,
  CurriculumLessonErrorResponseSchema,
  parseCurriculumLessonBlock,
  parseCurriculumLessonAggregateResponse,
  parseCurriculumLessonCheckResponse,
} from './curriculumLessonSchema';
export type {
  CurriculumLessonTextBlockData,
  CurriculumLessonExampleBlockData,
  CurriculumLessonVocabularyItem,
  CurriculumLessonMediaAsset,
  CurriculumLessonMultipleChoiceOption,
  CurriculumLessonMultipleChoiceConfig,
  CurriculumLessonExerciseExplanation,
  CurriculumLessonExercise,
  CurriculumLessonBlock,
  CurriculumLessonUnsupportedBlock,
  CurriculumLessonParsedBlock,
  CurriculumLesson,
  CurriculumLessonCheckAnswer,
  CurriculumLessonErrorCode,
  CurriculumLessonAggregateParseResult,
  CurriculumLessonCheckParseResult,
} from './curriculumLessonSchema';
export {
  fetchCurriculumLesson,
  checkCurriculumLessonExercise,
} from './curriculumLessonClient';
export type {
  CurriculumLessonErrorKind,
  CurriculumLessonError,
  CurriculumLessonResult,
  CurriculumLessonCheckResult,
  CurriculumLessonClientOptions,
  CurriculumLessonAnswerInput,
} from './curriculumLessonClient';
