import type {FeatureRegistryEntry} from './types';

export const featureRegistry = [
  {
    key: 'pasteTextInput',
    module: 'modules/input',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'imageInput',
    module: 'modules/input',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'ocrScanner',
    module: 'modules/ocr',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'ocrReviewEdit',
    module: 'modules/ocr',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'aiLessonAnalysis',
    module: 'modules/ai-analysis',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'lessonResultView',
    module: 'modules/lesson',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'lessonSave',
    module: 'modules/lesson',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'lessonHistory',
    module: 'modules/lesson',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'lingobitesMvpReviewFlow',
    module: 'app/navigation',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'shortPractice',
    module: 'modules/practice',
    required: false,
    releaseGroup: 'foundation',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'pronunciationSupport',
    module: 'modules/speaking',
    required: false,
    releaseGroup: 'foundation',
    status: 'not_implemented',
    limitations: ["Not implemented yet"],
  },
  {
    key: 'themeSystem',
    module: 'theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'themeSwitcher',
    module: 'theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'darkTheme',
    module: 'theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'pastelKidsTheme',
    module: 'theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'coreTheme',
    module: 'theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'neoTheme',
    module: 'theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'comicTheme',
    module: 'theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'cartoonTheme',
    module: 'theme',
    required: false,
    releaseGroup: 'ui',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'reviewSystem',
    module: 'modules/review',
    required: false,
    releaseGroup: 'practice',
    status: 'ready',
    entryPoint: 'HomeScreen -> PasteText',
  },
  {
    key: 'miniGame',
    module: 'modules/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ["Not implemented yet"],
  },
  {
    key: 'wordMatchGame',
    module: 'modules/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ["Not implemented yet"],
  },
  {
    key: 'fillBlankGame',
    module: 'modules/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ["Not implemented yet"],
  },
  {
    key: 'tenseQuizGame',
    module: 'modules/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ["Not implemented yet"],
  },
  {
    key: 'sentenceOrderGame',
    module: 'modules/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ["Not implemented yet"],
  },
  {
    key: 'flashcardChallenge',
    module: 'modules/engagement',
    required: false,
    releaseGroup: 'practice',
    status: 'not_implemented',
    limitations: ["Not implemented yet"],
  },
  {
    key: 'situationLearning',
    module: 'modules/content',
    required: false,
    releaseGroup: 'expansion',
    status: 'not_implemented',
    limitations: ["Not implemented yet"],
  },
  {
    key: 'dialogueGenerator',
    module: 'modules/content',
    required: false,
    releaseGroup: 'expansion',
    status: 'not_implemented',
    limitations: ["Not implemented yet"],
  },
  {
    key: 'phraseExtractor',
    module: 'modules/content',
    required: false,
    releaseGroup: 'expansion',
    status: 'not_implemented',
    limitations: ["Not implemented yet"],
  },
  {
    key: 'situationPractice',
    module: 'modules/content',
    required: false,
    releaseGroup: 'expansion',
    status: 'not_implemented',
    limitations: ["Not implemented yet"],
  },
] as const satisfies readonly FeatureRegistryEntry[];

export type FeatureKey = (typeof featureRegistry)[number]['key'];

export const featureKeys = featureRegistry.map(entry => entry.key);
